"use client";
import { useEffect, useMemo, useState } from "react";
import { Check, Copy, Download, FileCode2, Maximize2, Minimize2, X, Trash2, History } from "lucide-react";

type Props = { open:boolean; conversationId:string|null; messages:Array<{role:"user"|"assistant"|"system";content:string}>; onClose:()=>void };
type Version={id:string;title:string;content:string;createdAt:string};
function latest(messages:Props["messages"]){const m=[...messages].reverse().find(x=>x.role==="assistant");return {title:"Untitled artifact",content:m?.content??""};}
export default function CanvasWorkspace({open,conversationId,messages,onClose}:Props){
 const initial=useMemo(()=>latest(messages),[messages]); const [id,setId]=useState<string|null>(null); const [title,setTitle]=useState(initial.title); const [content,setContent]=useState(initial.content); const [saved,setSaved]=useState(false); const [expanded,setExpanded]=useState(false); const [versions,setVersions]=useState<Version[]>([]); const [showHistory,setShowHistory]=useState(false);
 useEffect(()=>{if(!open)return; setId(null);setVersions([]);setShowHistory(false); if(!conversationId){setTitle(initial.title);setContent(initial.content);return;} (async()=>{try{const r=await fetch(`/api/artifacts?conversationId=${encodeURIComponent(conversationId)}`);const d=await r.json();const a=d.artifacts?.[0];if(a){setId(a.id);setTitle(a.title);setContent(a.content);const v=await fetch(`/api/artifacts/${a.id}`);if(v.ok)setVersions((await v.json()).versions??[]);}else{setTitle(initial.title);setContent(initial.content);}}catch{setTitle(initial.title);setContent(initial.content);}})();},[open,conversationId,initial.title,initial.content]);
 async function save(){if(!conversationId)return;const body={title:title.trim()||"Untitled artifact",content};const r=id?await fetch(`/api/artifacts/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}):await fetch("/api/artifacts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...body,conversationId})});if(r.ok){const d=await r.json();setId(d.artifact.id);setTitle(d.artifact.title);setSaved(true);window.setTimeout(()=>setSaved(false),1400);const v=await fetch(`/api/artifacts/${d.artifact.id}`);if(v.ok)setVersions((await v.json()).versions??[]);}}
 function reset(){const n=latest(messages);setTitle(n.title);setContent(n.content);}
 async function remove(){if(!id||!confirm("Delete this artifact?"))return;const r=await fetch(`/api/artifacts/${id}`,{method:"DELETE"});if(r.ok){setId(null);setTitle(initial.title);setContent(initial.content);setVersions([]);}}
 async function copy(){try{await navigator.clipboard.writeText(content);setSaved(true);window.setTimeout(()=>setSaved(false),1000);}catch{}}
 function download(){const b=new Blob([content],{type:"text/plain;charset=utf-8"});const u=URL.createObjectURL(b);const a=document.createElement("a");a.href=u;a.download=(title.trim()||"artifact").replace(/[^a-z0-9_-]+/gi,"-")+".txt";a.click();URL.revokeObjectURL(u);}
 if(!open)return null;
 return <div className={expanded?"fixed inset-0 z-50 flex bg-background":"fixed inset-y-0 right-0 z-50 flex w-full max-w-2xl bg-background shadow-2xl"}><div className="flex min-w-0 flex-1 flex-col border-l"><header className="flex items-center gap-1 border-b px-3 py-2.5"><FileCode2 className="mr-1 size-4 text-muted-foreground"/><input value={title} onChange={e=>setTitle(e.target.value)} aria-label="Artifact title" className="min-w-0 flex-1 bg-transparent text-sm font-semibold outline-none"/><button onClick={save} aria-label="Save artifact" className="rounded-lg p-2 hover:bg-accent">{saved?<Check className="size-4"/>:<span className="text-xs font-medium">Save</span>}</button><button onClick={()=>setShowHistory(v=>!v)} aria-label="Artifact history" title="Artifact history" className="rounded-lg p-2 hover:bg-accent"><History className="size-4"/></button><button onClick={reset} aria-label="Use latest reply" className="rounded-lg p-2 text-xs hover:bg-accent">Reset</button><button onClick={copy} aria-label="Copy artifact" className="rounded-lg p-2 hover:bg-accent"><Copy className="size-4"/></button><button onClick={download} aria-label="Download artifact" className="rounded-lg p-2 hover:bg-accent"><Download className="size-4"/></button>{id?<button onClick={()=>void remove()} aria-label="Delete artifact" className="rounded-lg p-2 text-muted-foreground hover:text-destructive"><Trash2 className="size-4"/></button>:null}<button onClick={()=>setExpanded(v=>!v)} aria-label={expanded?"Collapse canvas":"Expand canvas"} className="rounded-lg p-2 hover:bg-accent">{expanded?<Minimize2 className="size-4"/>:<Maximize2 className="size-4"/>}</button><button onClick={onClose} aria-label="Close canvas" className="rounded-lg p-2 hover:bg-accent"><X className="size-4"/></button></header>{showHistory?<div className="max-h-40 overflow-auto border-b bg-muted/20 p-2">{versions.length?versions.map(v=><button key={v.id} onClick={()=>{setTitle(v.title);setContent(v.content);setShowHistory(false)}} className="block w-full rounded px-2 py-1.5 text-left text-xs hover:bg-accent">{new Date(v.createdAt).toLocaleString()} · {v.title}</button>):<p className="p-2 text-xs text-muted-foreground">No saved versions yet.</p>}</div>:null}<div className="flex min-h-0 flex-1 flex-col"><div className="border-b px-3 py-2 text-[11px] text-muted-foreground">Server-backed artifact · available across sessions</div><textarea value={content} onChange={e=>setContent(e.target.value)} spellCheck aria-label="Canvas editor" className="min-h-0 flex-1 resize-none bg-background px-4 py-4 font-mono text-sm leading-6 outline-none"/></div></div></div>;
}
